name: Lint and Test
on: [push]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx prettier --check "**/*.+(js|json|css|md|yml|yaml)"
      - run: npm run lint
      - run: npm test
