name: Lint and Test
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx prettier --check "**/*.+(js|json|css|md|yml|yaml)"
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm install
      - run: npm run lint
      - run: npm test
