name: Validate Build
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm ci
      - run: npx prettier --check "**/*.+(js|json|css|md|yml|hbs)"
      - run: npm run lint
      - run: npm test
      - run: npm run build && git diff >/dev/null --exit-code
